### PR TITLE
complete Weapon collision(not include bomb)

### PR DESCRIPTION
**Pull request by garry911128**
complete
1. Enemy class, with random direction move(i have commented it.)
2. Sword and Shield Rigidbody(I need to add a skeleton to continue to function as a weapon.)
3. GameManager, DebugInputManager.
4. i add the fox, and all weapon prefab.

### CODE REVIEW

**Review by kyynk — CHANGES_REQUESTED** [review]
1. To update the folder structure, you can change it as follows:

**Original Structure**:  
```
Resources  
|_ Enemy  
|_ Weapons  
```

**Updated Structure**:  
```
Resources  
|_ Prefabs  
   |_ Enemy  
   |_ Weapons  
```
2. Interface does not need to be specifically moved to a separate folder, since their namespace should be in the same location.

P.S. The namespace should match the folder name.

**Comment by kyynk** [comment]
> 1. To update the folder structure, you can change it as follows:
> 
> 
> **Original Structure**:
> 
> ```
> Resources  
> |_ Enemy  
> |_ Weapons  
> ```
> 
> **Updated Structure**:
> 
> ```
> Resources  
> |_ Prefabs  
>    |_ Enemy  
>    |_ Weapons  
> ```
> 
>     2. Interface does not need to be specifically moved to a separate folder, since their namespace should be in the same location.
> 
> 
> P.S. The namespace should match the folder name.

The second point refers to the image below.
image

**Comment by garry911128** [comment]
> > 1. To update the folder structure, you can change it as follows:
> > 
> > **Original Structure**:
> > ```
> > Resources  
> > |_ Enemy  
> > |_ Weapons  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Updated Structure**:
> > ```
> > Resources  
> > |_ Prefabs  
> >    |_ Enemy  
> >    |_ Weapons  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 2. Interface does not need to be specifically moved to a separate folder, since their namespace should be in the same location.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > P.S. The namespace should match the folder name.
> 
> The second point refers to the image below. image

**Comment by garry911128** [comment]
fix

**Review by kyynk — APPROVED** [review]
LGTM

**Pull request merged**
